---
- hosts: wug
  roles:
    - role: common
    - role: zzet.rbenv
    - { role: nginx, become: true }
    - role: zzet.postgresql
  tasks:
    - name: Downlaod nodejs
      become: true
      shell: creates=/usr/bin/node curl -sL https://deb.nodesource.com/setup_4.x | bash -
    - name: Install nodejs
      become: true
      apt: name=nodejs state=present

    - name: Install bundler gem
      gem: name=bundler state=present executable=/home/vagrant/.rbenv/shims/gem user_install=no
      tags: [gems]

    - name: Create database user
      postgresql_user: name={{dbuser}} password={{dbpassword}} role_attr_flags=CREATEDB,NOSUPERUSER
      tags: [database]

    - name: ensure database is created
      become: true
      become_user: postgres
      postgresql_db: name={{item}} owner=vagrant
      with_items: "{{databases}}"

    - name: ensure user has access to database
      become: true
      become_user: postgres
      postgresql_user: db={{item}} name={{dbuser}} password={{dbpassword}} priv=ALL role_attr_flags=CREATEDB
      with_items: "{{databases}}"

    - name: ensure user does not have unnecessary privilege
      postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,CREATEDB
